### ISSUE TITLE
Could you please remove assets/ai/wallpaper from the npm registry?

### ISSUE THREAD

**Issue by fourdim** [hejny/locate-app#6]
It seems that these files here are not required for locate-app to work.
And it takes up 27.8M of space in the node_modules.
See here for more:
https://www.npmjs.com/package/locate-app?activeTab=code

**Comment by s100** [comment]
Yeah what's the rationale behind this?

**Comment by hyandell** [comment]
+1. The images just seem to take up space, don't seem to be used, and are kinda weird being warped trademarks/logos from other projects.

**Comment by sipayRT** [comment]
+1 

The current size of the locate-app package is 28MB. This is quite large. When installing dependencies and using the package, these images are not actually used, but they are downloaded every time. Could you, please, move these images to some hosting and add links to them in the readme.md instead of using relative links from the package?

tnx

**Comment by KuznetsovRoman** [comment]
> move these images to some hosting

Or you could just add `assets` folder to the `.npmignore` file.

**Comment by naruaway** [comment]
FYI this seems to be already resolved for locate-app package in 9772e9e35c4b74b44c79af70e5c64a65d139cf50 but locate-app relies on `@promptbook/utils`, which relies on `spacetrim`, which happens to include large images. I filed PR there https://github.com/hejny/spacetrim/pull/9

**Comment by s100** [comment]
It's not fully resolved. `locate-app@2.4.8` still includes [a pointless 540kB wallpaper](https://github.com/hejny/locate-app/blob/main/media/locate-app-social-wallpaper.png).

**Comment by naruaway** [comment]
Ok sure, I missed that. I hope https://github.com/hejny/spacetrim/pull/9 will be merged & reviewed since it's about **38.7 MiB**. This is the largest package when installing `webdriverio`

**Comment by hejny** [comment]
Thank you for reporting this issue, now fixed in patch version `v2.4.9`.

**(it was a batch of non-ignored image files)**.
